Data Cleaning And Preprocessing

In [1]:
import pandas as pd
import numpy as np
np.set_printoptions(suppress = True, linewidth = 100, precision = 2)

In [2]:
raw_data = np.genfromtxt('loan-data.csv', delimiter = ';', skip_header= 1, autostrip= True)

In [3]:
raw_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [4]:
# Checking for missing data
np.isnan(raw_data).sum()

88005

In [5]:
#creating a temporary filler

temporary_fill = np.nanmax(raw_data) + 1
temporary_fill

68616520.0

In [6]:
temporary_mean = np.nanmean(raw_data, axis = 0)
temporary_mean

C:\Users\davsh\AppData\Local\Temp\ipykernel_4588\2836188066.py:1: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data, axis = 0)


array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [7]:
temporary_stat = np.array([np.nanmin(raw_data, axis = 0), np.nanmean(raw_data, axis = 0), np.nanmax(raw_data, axis = 0)])
temporary_stat

C:\Users\davsh\AppData\Local\Temp\ipykernel_4588\3017069630.py:1: RuntimeWarning: All-NaN slice encountered
  temporary_stat = np.array([np.nanmin(raw_data, axis = 0), np.nanmean(raw_data, axis = 0), np.nanmax(raw_data, axis = 0)])
C:\Users\davsh\AppData\Local\Temp\ipykernel_4588\3017069630.py:1: RuntimeWarning: Mean of empty slice
  temporary_stat = np.array([np.nanmin(raw_data, axis = 0), np.nanmean(raw_data, axis = 0), np.nanmax(raw_data, axis = 0)])


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [8]:
# identifying the strings columns
column_strings = np.argwhere(np.isnan(temporary_mean)).squeeze()
column_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [9]:
# identifying the numeric columns
column_numeric = np.argwhere(np.isnan(temporary_mean) == False).squeeze()
column_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [10]:
# dataset for only strings related columns
loan_data_strings = np.genfromtxt('loan-data.csv',
                                  delimiter = ';',
                                  autostrip = True,
                                  skip_header = 1,
                                  usecols = column_strings,
                                  dtype = 'str')

loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [11]:
# Dataset for numeric related data
loan_data_numeric = np.genfromtxt('loan-data.csv',
                                  delimiter = ';',
                                  autostrip = True,
                                  skip_header = 1,
                                  usecols = column_numeric,
                                  dtype = 'int',
                                  filling_values = temporary_fill)

loan_data_numeric

array([[48010226,    35000,    35000,       13,     1184,     9452],
       [57693261,    30000,    30000, 68616520,      938,     4679],
       [59432726,    15000,    15000, 68616520,      494,     1969],
       ...,
       [50415990,    10000,    10000, 68616520, 68616520,     2185],
       [46154151, 68616520,    10000,       16,      354,     3199],
       [66055249,    10000,    10000, 68616520,      309,      301]])

In [12]:
# getting the headers for each data
header_full = np.genfromtxt('loan-data.csv',
                                  delimiter = ';',
                                  autostrip = True,
                                  skip_footer = raw_data.shape[0] ,
                                  dtype = 'str')
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [13]:
header_strings, header_numeric = header_full[column_strings], header_full[column_numeric]

In [14]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [15]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

Creating a Checkpoint Function

In [16]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return checkpoint_variable

In [17]:
checkpoint_test = checkpoint('Checkpoint-test', header_strings, loan_data_strings)

In [18]:
checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [19]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [20]:
# Checking if the checkpoint data is same and the main data

np.array_equal(checkpoint_test['data'], loan_data_strings)

True

Data Preprocessing for the String Columns

In [21]:
# First column
header_strings[0]

'issue_d'

In [22]:
# remaining the column to 'issue_date'
header_strings[0] = 'issue_data'
header_strings[0]

'issue_data'

In [23]:
# Let's see the data inside this column

loan_data_strings[:, 0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [24]:
np.unique(loan_data_strings[:, 0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [25]:
# removing the -15 from each data

loan_data_strings[:, 0] = np.chararray.strip(loan_data_strings[:, 0], '-15')

In [26]:
np.unique(loan_data_strings[:, 0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [27]:
# converting each of the data in this column in its respective month number equivalent

month = ['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
for i in range(13):
    loan_data_strings[:, 0] = np.where(loan_data_strings[:, 0] == month[i], 
                                      i,
                                      loan_data_strings[:, 0])

In [28]:
np.unique(loan_data_strings[:, 0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [29]:
# Second column
header_strings[1]

'loan_status'

In [30]:
loan_data_strings[:, 1]

array(['Current', 'Current', 'Current', ..., 'Current', 'Current', 'Current'], dtype='<U69')

In [31]:
np.unique(loan_data_strings[:, 1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [32]:
# Categorizing this column into good(1) and bad(0) that where ['Current', 'Fully Paid', 'In Grace Period', 'Issued' 'Late(16-30 days')] are tag
# as good and the rest as bad
bad_status = ['', 'Charged Off', 'Default', 'Late (310-120 days)']
loan_data_strings[:, 1] = np.where(np.isin(loan_data_strings[:, 1], bad_status), 
                                  0,
                                  1)


In [33]:
np.unique(loan_data_strings[:, 1])

array(['0', '1'], dtype='<U69')

In [34]:
# Third column
header_strings[2]

'term'

In [35]:
header_strings[2] = 'term_month'
header_strings[2]

'term_month'

In [36]:
loan_data_strings[:, 2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      dtype='<U69')

In [37]:
np.unique(loan_data_strings[:, 2])

array(['', '36 months', '60 months'], dtype='<U69')

In [38]:
# removing the months to just leave only the number
loan_data_strings[:, 2] = np.chararray.strip(loan_data_strings[:, 2], ' months')

In [39]:
np.unique(loan_data_strings[:, 2])

array(['', '36', '60'], dtype='<U69')

In [40]:
# fixing the missing data and converting to int
loan_data_strings[:, 2] = np.where(loan_data_strings[:, 2] == '',
                                   60, 
                                   loan_data_strings[:, 2])

In [41]:
np.unique(loan_data_strings[:, 2])

array(['36', '60'], dtype='<U69')

In [42]:
# Fourth column
header_strings[3]

'grade'

In [43]:
loan_data_strings[:, 3]

array(['C', 'A', 'B', ..., 'A', 'D', 'A'], dtype='<U69')

In [44]:
np.unique(loan_data_strings[:, 3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [45]:
# There is a relationship between the grade column and the subgrade column

header_strings[4]

'sub_grade'

In [46]:
loan_data_strings[:, 4]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [47]:
np.unique(loan_data_strings[:, 4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [48]:
for i in np.unique(loan_data_strings[:, 3])[1:]:
    loan_data_strings[:, 4]= np.where((loan_data_strings[:, 4] == '') & (loan_data_strings[:, 3] == i), 
                    i + '5',
                    loan_data_strings[:, 4])

In [49]:
np.unique(loan_data_strings[:, 4], return_counts = True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [50]:
# We still have 9 missing data and we can just assign 'H1' to them
loan_data_strings[:, 4] = np.where(loan_data_strings[:, 4] == '',
                                   'H1',
                                   loan_data_strings[:, 4])

In [51]:
np.unique(loan_data_strings[:, 4], return_counts = True)

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9],
       dtype=int64))

In [52]:
# We can now effectively delete the grade column

loan_data_strings = np.delete(loan_data_strings, 3, axis = 1)
header_strings = np.delete(header_strings, 3)

In [53]:
loan_data_strings[:, 3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [54]:
keys = np.unique(loan_data_strings[:, 3])
values = list(range(1, len(np.unique(loan_data_strings[:, 3])) + 1))
dict_sub_grade = dict(zip(keys, values))

In [55]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [56]:
for i in np.unique(loan_data_strings[:, 3]):
    loan_data_strings[:, 3] = np.where(loan_data_strings[:, 3] == i, 
                                       dict_sub_grade[i],
                                       loan_data_strings[:, 3])

In [57]:
np.unique(loan_data_strings[:, 3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [58]:
# Forth Column
header_strings[4]

'verification_status'

In [59]:
loan_data_strings[:, 4]

array(['Verified', 'Source Verified', 'Verified', ..., 'Source Verified', 'Source Verified', ''],
      dtype='<U69')

In [60]:
np.unique(loan_data_strings[:, 4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [61]:
# Formating the verification status into dummie variables(0, 1)
not_verified = ['', 'Not Verified']
loan_data_strings[:, 4] = np.where(np.isin(loan_data_strings[:, 4], not_verified),
                                  0,
                                  1)

In [62]:
np.unique(loan_data_strings[:, 4])

array(['0', '1'], dtype='<U69')

In [63]:
# Fifth column
header_strings[5]

'url'

In [64]:
loan_data_strings[:, 5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [65]:
# the url column contain almost the same data throughout the dataset only for it last set of numbers which indicate the users id and this has 
# been capture in another column. So we delete the url column
loan_data_strings = np.delete(loan_data_strings, 5, axis = 1)
header_strings = np.delete(header_strings, 5)

In [66]:
header_strings[5]

'addr_state'

In [67]:
loan_data_strings[:, 5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [68]:
np.unique(loan_data_strings[:, 5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [69]:
np.unique(loan_data_strings[:, 5], return_counts = True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

In [70]:
np.unique(loan_data_strings[:, 5]).size

50

In [71]:
state_name, state_count = np.unique(loan_data_strings[:, 5], return_counts = True)
state_count_sorted = np.argsort(-state_count)
state_name[state_count_sorted], state_count[state_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [72]:
# filling the missing data 
loan_data_strings[:, 5] = np.where(loan_data_strings[:, 5] == '',
                                   0, 
                                   loan_data_strings[:, 5])

In [73]:
np.unique(loan_data_strings[:, 5])

array(['0', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [74]:
# This addr_state column give the exact total number of states in the United States of American, So we categorize them into their geopolitical zones
states_west = np.array(['WA', 'OR', 'CA', 'NV', 'ID', 'MT', 'WY', 'UT', 'CO', 'AZ', 'NM', 'HI', 'AK'])
states_south = np.array(['TX', 'OK', 'AR', 'LA', 'MS', 'AL', 'TN', 'KY', 'FL', 'GA', 'SC', 'NC', 'VA', 'WV', 'MD', 'DE', 'DC'])
states_midwest = np.array(['ND', 'SD', 'NE', 'KS', 'MN', 'IA', 'MO', 'WI', 'IL', 'IN', 'MI', 'OH'])
states_east = np.array(['PA', 'NY', 'NJ', 'CT', 'MA', 'VT', 'NH', 'ME', 'RI'])

In [75]:
loan_data_strings[:, 5] = np.where(np.isin(loan_data_strings[:, 5], states_west), 1, loan_data_strings[:, 5])
loan_data_strings[:, 5] = np.where(np.isin(loan_data_strings[:, 5], states_south), 2, loan_data_strings[:, 5])
loan_data_strings[:, 5] = np.where(np.isin(loan_data_strings[:, 5], states_midwest), 3, loan_data_strings[:, 5])
loan_data_strings[:, 5] = np.where(np.isin(loan_data_strings[:, 5], states_east), 4, loan_data_strings[:, 5])

In [76]:
np.unique(loan_data_strings[:, 5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

In [77]:
loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [78]:
loan_data_strings = loan_data_strings.astype(int)

In [79]:
loan_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

Checkpoint

In [80]:
checkpoint_strings = checkpoint("Checkpoint-Strings", header_strings, loan_data_strings)

In [81]:
checkpoint_strings['header']

array(['issue_data', 'loan_status', 'term_month', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [82]:
checkpoint_strings['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

Numeric Columns

In [83]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [84]:
loan_data_numeric

array([[48010226,    35000,    35000,       13,     1184,     9452],
       [57693261,    30000,    30000, 68616520,      938,     4679],
       [59432726,    15000,    15000, 68616520,      494,     1969],
       ...,
       [50415990,    10000,    10000, 68616520, 68616520,     2185],
       [46154151, 68616520,    10000,       16,      354,     3199],
       [66055249,    10000,    10000, 68616520,      309,      301]])

In [85]:
# Checking for missing data
np.isnan(loan_data_numeric).sum()

0

In [86]:
loan_data_numeric[:, 0]

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [87]:
# checking if any of the first column was filled with the temporry fil
np.isin(loan_data_numeric[:, 0], temporary_fill).sum()

0

In [88]:
temporary_stat

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [89]:
temporary_stat[:, column_numeric]
# the first row represent the min values, followed by the mean and then the max

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [90]:
# funded_amt
loan_data_numeric[:, 2]

array([35000, 30000, 15000, ..., 10000, 10000, 10000])

In [91]:
# Replacing every temporary_fill values in the funded_amt with the min of the the column
loan_data_numeric[:, 2] = np.where(loan_data_numeric[:, 2] == temporary_fill, 
                                   temporary_stat[0, column_numeric[2]],
                                   loan_data_numeric[:, 2])


In [92]:
np.isin(loan_data_numeric[:, 2], temporary_fill).sum()

0

In [93]:
# working the other columns that is 'loan_amnt', 'int_rate', 'installment', 'total_pymnt'
# the columns have the index of 1, 3, 4, 5
# using a for loop to fill the max values from the temporary_stat into all these columns 

for i in [1, 3, 4, 5]:
    loan_data_numeric[:, i] = np.where(loan_data_numeric[:, i] == temporary_fill,
                                      temporary_stat[2, column_numeric[i]],
                                      loan_data_numeric[:, i]) 


In [94]:
loan_data_numeric

array([[48010226,    35000,    35000,       13,     1184,     9452],
       [57693261,    30000,    30000,       28,      938,     4679],
       [59432726,    15000,    15000,       28,      494,     1969],
       ...,
       [50415990,    10000,    10000,       28,     1372,     2185],
       [46154151,    35000,    10000,       16,      354,     3199],
       [66055249,    10000,    10000,       28,      309,      301]])

Currency Change

In [95]:
# Exchange dataset
EUR_USD = np.genfromtxt('EUR-USD.csv', delimiter =',', autostrip = True, dtype = 'str')
EUR_USD

array([['Open', 'High', 'Low', 'Close', 'Volume'],
       ['1.2098628282546997', '1.2098628282546997', '1.11055588722229', '1.1287955045700073', '0'],
       ['1.1287955045700073', '1.1484194993972778', '1.117680549621582', '1.1205360889434814',
        '0'],
       ['1.119795799255371', '1.1240400075912476', '1.0460032224655151', '1.0830246210098267',
        '0'],
       ['1.0741022825241089', '1.1247594356536865', '1.0521597862243652', '1.1114321947097778',
        '0'],
       ['1.1215037107467651', '1.145304799079895', '1.0821995735168457', '1.0960345268249512',
        '0'],
       ['1.095902442932129', '1.1428401470184326', '1.0888904333114624', '1.122296690940857', '0'],
       ['1.1134989261627197', '1.1219995021820068', '1.081270456314087', '1.0939244031906128',
        '0'],
       ['1.0969001054763794', '1.1705996990203857', '1.0850305557250977', '1.1340054273605347',
        '0'],
       ['1.1225990056991577', '1.1460003852844238', '1.1089695692062378', '1.1255937814712524

In [96]:
# since we will only be using the "Close" column we can only import just that column
EUR_USD = np.genfromtxt('EUR-USD.csv', delimiter =',', autostrip = True, skip_header = 1, usecols = 3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [97]:
loan_data_strings[:, 0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [98]:
# attributing exchange rate for each of the issued_data
exchange_rate = loan_data_strings[:, 0]

for i in range(1, 13):
    exchange_rate = np.where(exchange_rate == i,
                             EUR_USD[i - 1],
                             exchange_rate)

exchange_rate = np.where(exchange_rate == 0,
                             np.mean(EUR_USD),
                             exchange_rate)
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [99]:
exchange_rate.shape

(10000,)

In [100]:
loan_data_numeric.shape

(10000, 6)

In [101]:
# In other to stack the exchange_rate into the loan_data_numeric, we need to change the shape of the exchange_rate

exchange_rate = np.reshape(exchange_rate, (10000, 1))
exchange_rate.shape

(10000, 1)

In [102]:
# Horizotal stalking

loan_data_numeric = np.hstack((loan_data_numeric, exchange_rate))
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.  ,     9452.  ,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.  ,     4679.  ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.  ,     1969.  ,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.  ,     2185.  ,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.  ,     3199.  ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.  ,      301.  ,        1.09]])

In [103]:
# Also stalking the header 

header_numeric = np.hstack((header_numeric, np.array(['exchange_rate'])))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [104]:
# columns that indicated amount in dollars
columns_dollars = np.array([1, 2, 4, 5])

In [105]:
loan_data_numeric[:, columns_dollars]

array([[35000., 35000.,  1184.,  9452.],
       [30000., 30000.,   938.,  4679.],
       [15000., 15000.,   494.,  1969.],
       ...,
       [10000., 10000.,  1372.,  2185.],
       [35000., 10000.,   354.,  3199.],
       [10000., 10000.,   309.,   301.]])

In [106]:
loan_data_numeric[:, 6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [107]:
# creating new columns where we convert all the dollar to EUR equivalent
for i in columns_dollars:
    loan_data_numeric = np.hstack((loan_data_numeric, np.reshape((loan_data_numeric[:, i] / loan_data_numeric[:, 6]), (10000, 1))))

In [108]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1080.26,     8623.82],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.34,     4231.76],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      438.88,     1749.3 ],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1222.49,     1946.9 ],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.51,     2878.27],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      282.61,      275.29]])

In [109]:
loan_data_numeric.shape

(10000, 11)

Expanding the headers name

In [110]:
header_additional = np.array([column_name + '_EUR' for column_name in header_numeric[columns_dollars]])

header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [111]:
# Stacking the additional columns names with header_numeric

header_numeric = np.hstack((header_numeric, header_additional))
header_numeric 

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [112]:
#adding '_USD' to the dollar amount 

for i in header_numeric[columns_dollars]:
    header_numeric = np.where(header_numeric == i,
                             i + '_USD', 
                             header_numeric)

header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [113]:
col_rearrange  = [0, 1, 7, 2, 8, 3, 4, 9, 5,10, 6]

In [114]:
header_numeric = header_numeric[col_rearrange]
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [115]:
loan_data_numeric =loan_data_numeric[:, col_rearrange]
loan_data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.  ,     8623.82,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.  ,     4231.76,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.  ,     1749.3 ,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.  ,     1946.9 ,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.  ,     2878.27,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.  ,      275.29,        1.09]])

In [116]:
checkpoint_numeric = checkpoint('Checkpoint-Numeric', header_numeric, loan_data_numeric)

In [117]:
checkpoint_numeric['data']

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.  ,     8623.82,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.  ,     4231.76,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.  ,     1749.3 ,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.  ,     1946.9 ,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.  ,     2878.27,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.  ,      275.29,        1.09]])

In [118]:
checkpoint_numeric['header']

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

Creating A Complete Dataset

In [119]:
checkpoint_strings['data'].shape

(10000, 6)

In [120]:
checkpoint_numeric['data'].shape

(10000, 11)

In [121]:
loan_data = np.hstack((checkpoint_numeric['data'], checkpoint_strings['data']))

In [122]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [123]:
loan_data.shape

(10000, 17)

In [124]:
np.isnan(loan_data).sum()

0

In [125]:
header_full = np.concatenate([checkpoint_numeric['header'], checkpoint_strings['header']])

In [126]:
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue_data', 'loan_status', 'term_month', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [127]:
header_full[-1] = 'state_address'

In [128]:
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue_data', 'loan_status', 'term_month', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [129]:
np.argsort(loan_data[:, 0])

array([2086, 4812, 2353, ..., 4935, 9388, 8415], dtype=int64)

In [130]:
loan_data = loan_data[np.argsort(loan_data[:, 0])]

In [131]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [132]:
np.argsort(loan_data[:, 0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

In [133]:
# Combining the header_full to the loan_data

loan_data = np.vstack((header_full, loan_data))

In [134]:
loan_data

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'state_address'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [135]:
# Saving the dataset
np.savetxt('loan-data-preprocessing.csv', 
           loan_data, 
           fmt ="%s", 
           delimiter=',')